const appStore = { label: 'Podpin on the App Store — availability and requirements', url: 'https://apps.apple.com/us/app/ai-podcast-player-podpin/id6760191862' };

export default [
  {
    slug: 'ai-podcast-player', locale: 'en', group: 'features',
    title: 'AI Podcast Player for Listening and Learning | Podpin',
    heading: 'An AI podcast player for the ideas you want to keep',
    description: 'Listen, read transcripts, explore summaries, and save meaningful highlights with Podpin, an AI podcast player for iPhone, iPad, and Mac.',
    intro: 'An interesting episode should leave you with more than a vague memory. Podpin brings listening, transcripts, AI summaries, and personal highlights into one podcast player, so you can return to the ideas that mattered.',
    image: 'player', imageAlt: 'Podpin podcast player on iPhone',
    sections: [
      { heading: 'Go from listening to understanding', paragraphs: ['A traditional player helps you finish an episode. An AI podcast player adds ways to work with what you heard: read the words, find a topic, review the structure, and keep a useful passage. Podpin combines those tools with podcast playback on Apple devices.', 'Use an episode summary to get oriented. Explore chapters when you want to revisit one part of a conversation. Read the transcript when a technical term or a fast explanation needs a second look. These are different views of the same episode, not substitutes for judging its ideas.'] },
      { heading: 'Keep your takeaways separate from the AI’s', paragraphs: ['A summary describes what an episode covers. A personal note explains why a particular moment matters to you. Podpin lets you save highlights, add notes, and use colors to organize them.', 'For example, a product interview might contain a useful way to phrase a research question. Save the passage, then add a note such as: “Try this opening question in the next customer interview.” You now have both the source and a reason to revisit it.'], bullets: ['Transcripts help you locate the original words.', 'Summaries, insights, and chapters help you navigate.', 'Highlights and notes preserve your own interpretation.', 'References give you leads to investigate beyond the episode.'] },
      { heading: 'Designed around your Apple devices', paragraphs: ['Podpin is available for iPhone, iPad, and Mac, with optional CloudKit sync for your library, highlights, and listening progress. Sync availability depends on your plan and setup. That supports a simple rhythm: listen on your phone and return to the material when you have time to think.', 'Transcription runs on-device. Supported AI summarization workflows offer a local mode and optional cloud processing; choose the mode that fits your preferences. Check the current App Store listing and in-app setup for supported devices, operating systems, model availability, and downloads. Installing a player does not guarantee every AI feature is available on every device.'] },
      { heading: 'Start with one episode you actually need', paragraphs: ['Choose a conversation related to something you are learning or doing. Keep one useful highlight, write one sentence in your own words, and revisit the source when you use the idea. That small loop is a more practical test than collecting dozens of summaries.', 'Generated transcripts and summaries can contain mistakes. Check names, numbers, quotations, and important claims against the audio and the original sources before relying on them.'] }
    ],
    faq: [
      { q: 'What does AI add to a podcast player?', a: 'It can turn audio into searchable text and provide summaries, chapters, insights, and reference suggestions. The useful result is easier navigation and review; the listener still decides which ideas are worth keeping.' },
      { q: 'Can I use Podpin as an ordinary podcast player?', a: 'Podcast playback is part of Podpin. AI tools and personal notes extend that listening experience. Check the current app for feature availability and any setup requirements.' }
    ],
    related: ['on-device-podcast-transcription', 'podcast-app-with-notes', 'guides/podcast-learning-workflow'], sources: [appStore], updated: '2026-08-30'
  },
  {
    slug: 'private-ai-podcast-player', locale: 'en', group: 'features',
    title: 'Private AI Podcast Player: On-Device Transcription | Podpin',
    heading: 'Choose on-device AI for your podcast workflow',
    description: 'Understand Podpin’s on-device transcription approach, how it differs from cloud sync, and what to check when choosing a private AI podcast player.',
    intro: 'If privacy matters to you, ask where each part of a podcast app’s work happens. Podpin uses on-device transcription and offers local and optional cloud AI modes for supported summarization. Choose on-device mode when local AI processing is your priority.',
    image: 'episode-detail', imageAlt: 'Podpin episode detail and transcript view',
    sections: [
      { heading: 'Local processing, cloud AI, and sync are different choices', paragraphs: ['On-device transcription describes where podcast audio is converted into text: on your device. For supported summarization workflows, Podpin also offers local AI and an optional cloud AI mode. Check your chosen mode rather than assuming all generated content is always processed locally.', 'Optional CloudKit sync moves supported library, highlight, and progress information between your devices and depends on your plan and setup. This is separate from AI processing. Do not read “on-device” as a promise that the entire app never connects to the internet or that every category of data stays in one place.'] },
      { heading: 'Evaluate a private podcast app feature by feature', paragraphs: ['Your listening history and your personal notes are not the same kind of information as publicly distributed episode audio. A useful privacy review considers what you add to the app as well as what you listen to.', 'Podpin’s App Store privacy disclosure lists usage and diagnostic data that may be collected without being linked to your identity. That is another reason not to equate local AI with zero data collection. Read the current privacy policy for the full context before building a sensitive workflow.'], bullets: ['Processing: where does transcription run?', 'Connectivity: what needs a download or network connection?', 'Sync: which information is shared between your devices?', 'Personal notes: what information are you choosing to save?', 'Controls: what do current settings and policies say about your data?'] },
      { heading: 'Know what local AI needs', paragraphs: ['Local processing still requires compatible hardware and software. Check the current Podpin listing and setup screens for device support, operating-system requirements, models, and any necessary downloads. Allow time for setup before expecting to transcribe an episode.', 'Performance depends on the device and workload. We do not promise a fixed processing time, battery saving, or perfect recognition. If you need a particular episode while travelling, verify the needed audio and features on your device beforehand.'] },
      { heading: 'Keep notes useful without oversharing', paragraphs: ['A podcast note can be specific without containing confidential details. Instead of recording a customer’s full personal information, write the general question you want to investigate and keep sensitive records in the system intended for them.', 'Try Podpin with a public episode and a few non-sensitive highlights first. Confirm how the workflow behaves across your Apple devices, then decide whether its processing and syncing approach meets your needs.'] }
    ],
    faq: [
      { q: 'Does on-device transcription mean Podpin is completely offline?', a: 'No. Transcription runs locally, but optional cloud AI, podcast discovery, audio or model downloads, and CloudKit sync involve separate connectivity considerations. Choose local AI mode and verify the specific features you need before relying on an offline workflow.' },
      { q: 'Does this page replace the privacy policy?', a: 'No. The privacy policy, App Store disclosures, and current app settings are the appropriate places to check data practices. This page explains the distinction between local processing and synchronization.' }
    ],
    related: ['on-device-podcast-transcription', 'guides/choose-ai-podcast-app', 'podcast-app-for-iphone'], sources: [appStore], updated: '2026-08-30'
  },
  {
    slug: 'on-device-podcast-transcription', locale: 'en', group: 'features',
    title: 'On-Device Podcast Transcription | Podpin',
    heading: 'Read the podcast, then return to the moment',
    description: 'Podpin turns podcast audio into text with on-device transcription. Read along, search for an idea, and check the original moment in the episode.',
    intro: 'A transcript gives spoken ideas a second way in. Podpin’s on-device podcast transcription helps you read an explanation, search for a term, and return to the audio when the wording or context matters.',
    image: 'episode-detail', imageAlt: 'Episode details in the Podpin podcast app',
    sections: [
      { heading: 'A transcript is a working layer over the audio', paragraphs: ['A long conversation can be easy to follow while it plays and hard to navigate later. Text changes that. You can look for a distinctive word, reread a dense passage, or work out where an explanation starts without repeatedly guessing a playback position.', 'Podpin connects transcripts with the listening experience. Use the text to find the relevant part, then listen again before saving a quotation or interpreting a claim. The audio remains the source; the transcript is a tool for getting back to it.'] },
      { heading: 'What on-device transcription means', paragraphs: ['Transcription converts speech into written text. Podpin performs that work on the device. This is separate from obtaining podcast audio, downloading required models, optional CloudKit sync, and the local or optional cloud mode used for supported AI summaries.', 'Before starting, check the current App Store requirements and in-app setup. Supported hardware, software versions, language or model availability, free storage, and required downloads can affect whether a transcription workflow is ready. We do not claim identical results or processing speed on every Apple device.'] },
      { heading: 'Try a passage with a clear purpose', paragraphs: ['Imagine an interview in which a guest explains the difference between an observation and an assumption. Search for one of those terms, read the surrounding exchange, and replay it. If the distinction helps your work, save a highlight and write your own example.', 'The same approach works for an unfamiliar book title, a technical phrase, or the steps in a method. Start with a short, distinctive query. If the expected spelling produces nothing, try a simpler term from the same discussion.'], steps: ['Choose an episode and complete any transcription setup shown in the app.', 'Read or search its available transcript for a useful passage.', 'Return to the audio to check meaning and wording.', 'Save the relevant moment with a note about why you need it.'] },
      { heading: 'Treat generated text as a draft of what was said', paragraphs: ['Speech recognition can struggle with overlapping voices, unusual names, accents, specialist terms, and poor recordings. A polished-looking transcript can still contain a wrong word or missing negation.', 'For anything you plan to quote, publish, or use in an important decision, replay the passage and check the original reference. A transcript makes verification easier; it does not remove the need for it.'] }
    ],
    faq: [
      { q: 'Is a transcript the same as a summary?', a: 'No. A transcript represents the spoken words. A summary condenses selected ideas and leaves details out. Use a transcript for wording and context, and a summary for an overview.' },
      { q: 'Does Podpin transcribe every language on every device?', a: 'Do not assume universal language or hardware support. Check the current app and its requirements for the episode language and the device you intend to use.' }
    ],
    related: ['search-podcast-transcripts', 'private-ai-podcast-player', 'guides/transcripts-summaries-highlights'], sources: [appStore], updated: '2026-08-30'
  },
  {
    slug: 'podcast-app-with-notes', locale: 'en', group: 'features',
    title: 'Podcast App with Notes, Bookmarks, and Highlights | Podpin',
    heading: 'Keep the moment. Add what it means to you.',
    description: 'Save podcast highlights, add personal notes, and organize important moments with colors in Podpin for iPhone, iPad, and Mac.',
    intro: 'A bookmark tells you where to return. A note tells you why. Podpin puts highlights and personal notes alongside podcast listening, helping useful moments survive beyond the end of an episode.',
    image: 'library-light', imageAlt: 'Podpin library in light appearance',
    sections: [
      { heading: 'One saved moment, two kinds of information', paragraphs: ['The episode contains what the speaker said. Your note contains what you made of it: an unanswered question, a connection to a project, or something you want to try. Keeping these separate makes your library easier to trust and revisit.', 'Podpin lets you bookmark moments, add notes to highlights, and use colors for organization. You do not have to write a complete episode recap. Often, one sentence attached to the right passage is more useful than a page of disconnected notes.'] },
      { heading: 'Make notes you can recognize a week later', paragraphs: ['“Interesting” records your reaction but gives you little to work with. “Compare this interview method with our onboarding questions” supplies a topic and a next step. Give future-you enough information to understand the value without replaying the entire episode.', 'For example, after hearing an author distinguish a habit from a goal, save the moment and write: “My goal is reading more; the habit could be ten pages after breakfast.” This is an illustrative note, not a claim that the method will work for everyone.'], bullets: ['Idea: explain the takeaway in your own words.', 'Context: name the project, question, or situation it relates to.', 'Next step: write what you want to check, try, or discuss.', 'Uncertainty: record where you disagree or need evidence.'] },
      { heading: 'Use colors with a small, consistent meaning', paragraphs: ['A color system only helps if you remember what it means. Start with a few categories, such as ideas to try, sources to investigate, and questions to discuss. These are suggested conventions for your own highlights, not automatic classifications.', 'If every passage receives a highlight, review becomes another full listen. Save selectively. A library of useful moments should help you choose what matters, not preserve every sentence just in case.'] },
      { heading: 'Return to the source on your Apple devices', paragraphs: ['Podpin supports optional CloudKit sync for your library, highlights, and listening progress across its Apple-device experience. You can listen in one setting and make time for review in another, subject to your plan, device, and sync setup.', 'Before depending on a particular workflow, check current compatibility and feature availability. This page does not promise third-party note exports, a web editor, or hands-free capture. If those are essential, make them explicit items in your app evaluation.'] }
    ],
    faq: [
      { q: 'Should I bookmark a moment or write a full note?', a: 'Capture the moment first when you have limited time. When you can review it, add a sentence about why it matters. You only need a longer note when the idea genuinely needs more explanation.' },
      { q: 'Can I organize podcast highlights with colors?', a: 'Podpin supports color-coded highlights. Choose your own small set of meanings and apply them consistently so the colors help you review.' }
    ],
    related: ['guides/take-podcast-notes', 'guides/bookmark-podcast-moments', 'guides/remember-podcasts'], sources: [appStore], updated: '2026-08-30'
  },
  {
    slug: 'search-podcast-transcripts', locale: 'en', group: 'features',
    title: 'Search Podcast Transcripts and Find Ideas Again | Podpin',
    heading: 'Find the idea you remember hearing',
    description: 'Use Podpin’s searchable podcast transcripts to find a phrase, revisit an explanation, and save the original moment with a useful note.',
    intro: 'You remember the idea, but not the episode title or the point in the conversation. Searchable podcast transcripts give you a route back through the words, instead of another round of scrubbing through audio.',
    image: 'episode-detail', imageAlt: 'Podpin episode view for reading and revisiting podcast content',
    sections: [
      { heading: 'Search what was said, not just the title', paragraphs: ['An episode title might describe a guest or a broad theme without mentioning the detail you need. Transcript search works with the text of an available transcript, so a phrase from the conversation can be a better starting point than its headline.', 'Podpin brings search into your transcript workflow. Begin with a distinctive name, concept, or phrase, then inspect the surrounding passage. Search only has something to find when the relevant transcript exists; it is not a promise to search every podcast ever published.'] },
      { heading: 'Use a search ladder when your first query fails', paragraphs: ['Memory often preserves meaning rather than exact wording. If you remember a speaker discussing “avoiding wasted work,” they may have used “rework,” “constraints,” or “scope.” Try related terms one at a time and check promising sections.', 'Names and specialist words can also be transcribed differently from their official spelling. A common word spoken nearby may be easier to find than the name itself. No result does not prove the topic was absent.'], steps: ['Start with a short, distinctive term you remember.', 'Try a simpler version or a related phrase if necessary.', 'Use the likely episode, guest, or topic to narrow your review.', 'Read before and after a match, then replay the passage.', 'Save the useful moment so you do not have to repeat the search.'] },
      { heading: 'Recover an explanation, not just an isolated sentence', paragraphs: ['Suppose you want to revisit an example about interviewing customers. A match for “interview” might land in the guest introduction, not the explanation. Look for the actual argument and the example that supports it.', 'Once you find the right part, add a note describing the use you have in mind: “An example of asking about past behavior rather than hypothetical choices.” That note makes the recovered material easier to recognize later.'] },
      { heading: 'Verify before using a search result as evidence', paragraphs: ['Transcripts can contain recognition errors, and search results are only fragments of a conversation. Check who is speaking, whether they are quoting someone else, and whether the following sentence changes the meaning.', 'For a publication or research note, listen again and record the show, episode, speaker, and timestamp. If the speaker refers to a study or book, locate that original source rather than treating the podcast transcript as independent confirmation.'] }
    ],
    faq: [
      { q: 'Can transcript search find an idea if I forget the exact quote?', a: 'Try distinctive terms and alternative wording. A transcript records words, while your memory may retain a paraphrase. Do not assume every search supports semantic matching or every podcast is indexed.' },
      { q: 'Why might a word be missing from search results?', a: 'The relevant transcript may not be available, the speaker may have used different wording, or speech recognition may have rendered the term differently. Review the likely section of the audio when search is inconclusive.' }
    ],
    related: ['guides/find-a-podcast-quote', 'on-device-podcast-transcription', 'podcast-app-with-notes'], sources: [appStore], updated: '2026-08-30'
  },
  {
    slug: 'podcast-app-for-iphone', locale: 'en', group: 'features',
    title: 'Podcast App for iPhone with Transcripts and Notes | Podpin',
    heading: 'Make more of the podcasts you hear on iPhone',
    description: 'Podpin combines iPhone podcast listening with on-device transcription, summaries, highlights, and notes for the moments you want to revisit.',
    intro: 'Your iPhone is often where you hear a useful idea first. Podpin brings podcast playback, transcripts, and personal highlights together, so you can save the moment and think about it when you have time.',
    image: 'player', imageAlt: 'Podpin now playing interface on iPhone',
    sections: [
      { heading: 'Let listening and review happen at different times', paragraphs: ['Not every listening session is a study session. You might enjoy a conversation while taking a break, then want to return to one explanation at your desk. A useful iPhone podcast app should support both modes without asking you to annotate every minute.', 'In Podpin, playback sits alongside transcripts, summaries, chapters, and highlights. When it is safe and convenient to interact with your phone, save the part you want to revisit. Later, read the passage and add the context that makes it useful.'] },
      { heading: 'Keep a short note instead of switching contexts', paragraphs: ['A separate notes app can hold your thoughts, but a note without the episode context is easy to lose. Podpin lets you add personal notes to highlights and organize them with colors, keeping your interpretation close to the listening material.', 'For instance, save a passage about preparing for a difficult conversation and add: “Write the question before planning the answer.” On review, check the speaker’s full explanation and decide whether that advice fits your situation. The note is a prompt, not an endorsement of everything in the episode.'] },
      { heading: 'Prepare the device before you rely on AI', paragraphs: ['The App Store listing checked on August 30, 2026 requires iOS 26.0 or later. That installation requirement is not a guarantee that every AI feature works on every compatible iPhone. Follow in-app instructions for model availability and any necessary downloads.', 'Podpin’s transcription runs on-device; supported AI summaries also have an optional cloud mode. Before a journey, check that the episode audio and the specific tools you need are ready. Discovery, downloads, cloud AI, and synchronization have separate connectivity needs.'], bullets: ['Confirm your iPhone and operating-system compatibility.', 'Complete any setup or model downloads shown in the app.', 'Try one representative episode and inspect the transcript.', 'Check how your saved highlights appear on your other devices.'] },
      { heading: 'Continue with a larger screen when it helps', paragraphs: ['Podpin also supports iPad and Mac, with optional CloudKit sync for your library, highlights, and listening progress. Check your plan and sync settings. The phone can be where you listen; a later session can be where you compare ideas and write a fuller note.', 'Start with one show you already value. The best test is whether you can recover one useful moment and explain it in your own words, not how many new episodes you can add to a queue.'] }
    ],
    faq: [
      { q: 'Does Podpin also work on Mac and iPad?', a: 'Podpin is available for iPhone, iPad, and Mac. Optional CloudKit sync supports your library, highlights, and progress. Check current device requirements, plan availability, and your sync setup.' },
      { q: 'Can I safely capture notes while driving?', a: 'Do not interact with your phone while driving or in another situation that needs your attention. This page does not claim a hands-free capture feature. Wait until it is safe to review or save the moment.' }
    ],
    related: ['podcast-app-for-mac', 'podcast-app-with-notes', 'guides/bookmark-podcast-moments'], sources: [appStore], updated: '2026-08-30'
  },
  {
    slug: 'podcast-app-for-mac', locale: 'en', group: 'features',
    title: 'Podcast App for Mac with Transcripts and Highlights | Podpin',
    heading: 'Give podcast ideas a place in your desk workflow',
    description: 'Use Podpin on Mac to listen, read podcast transcripts, and review highlights and notes, with optional CloudKit sync across Apple devices.',
    intro: 'A Mac is a useful place to turn a remembered conversation into a considered note. Podpin brings podcast listening, transcripts, summaries, and highlights to macOS, alongside the work you want those ideas to inform.',
    image: 'library-dark', imageAlt: 'Podpin library interface in dark appearance',
    sections: [
      { heading: 'Move from background listening to focused review', paragraphs: ['Background listening and careful study ask for different kinds of attention. When an episode raises an idea worth using, set aside a short review session. Read the relevant passage, replay its context, and decide what belongs in your work.', 'Podpin gives you transcripts, episode summaries, insights, and chapters as ways back into the material. On a desk setup, the useful question is not simply “What did this episode say?” but “Which part changes what I will write, build, or investigate?”'] },
      { heading: 'Make the saved moment useful for a real project', paragraphs: ['Suppose you are drafting an article about how teams make decisions. An interview contains an example of someone changing their mind. Return to that passage, record what changed their view, and distinguish their account from your interpretation.', 'Add a personal note to the highlight with the question it informs. Use colors consistently if you want to separate examples, open questions, and sources to check. These are suggested ways to organize your own thinking, not proof that the speaker’s explanation is correct.'] },
      { heading: 'Connect phone listening with Mac review', paragraphs: ['Podpin supports iPhone, iPad, and Mac, with optional CloudKit sync for your library, highlights, and listening progress. That makes a phone-to-desk routine possible without treating the devices as separate listening projects.', 'Check your plan, app version, device compatibility, and sync setup before depending on a specific handoff. A sync feature should not be confused with an export integration: this page does not promise automatic delivery to Notion, Obsidian, or another notes service.'], steps: ['Listen to an episode and save a relevant highlight.', 'Make time to review the material on your Mac.', 'Read the transcript and replay important wording.', 'Write a note that connects the idea to a specific question.', 'Keep the source details when using the idea elsewhere.'] },
      { heading: 'Check Mac and AI requirements first', paragraphs: ['The App Store listing checked on August 30, 2026 requires macOS 26.0 or later and a Mac with Apple M1 or later. Check in-app setup for AI model availability and any downloads. Transcription runs on-device; supported summaries offer local AI and an optional cloud mode.', 'Generated text is useful for navigation but can mishear names or omit important nuance. Before citing a quotation or acting on a consequential claim, check the audio and any original reference. The larger review workspace helps you inspect an idea; it does not validate it automatically.'] }
    ],
    faq: [
      { q: 'Is Podpin a web podcast player?', a: 'This page describes the Podpin app for Mac and its Apple-device workflow. It does not promise a browser-based player or web note editor.' },
      { q: 'Can I review highlights saved while listening on iPhone?', a: 'Podpin supports optional CloudKit sync for highlights, library information, and progress. Confirm your plan, the current app versions, and sync setup on your devices before relying on a particular workflow.' }
    ],
    related: ['podcast-app-for-iphone', 'guides/podcast-learning-workflow', 'guides/find-a-podcast-quote'], sources: [appStore], updated: '2026-08-30'
  },
  {
    slug: 'guides/remember-podcasts', locale: 'en', group: 'guides',
    title: 'How to Remember What You Hear in Podcasts | Podpin',
    heading: 'Remember the useful part, not the whole episode',
    description: 'A practical podcast review routine: choose a question, save a meaningful moment, explain it in your own words, and return to it when it matters.',
    intro: 'You do not need to remember every episode. You need a way to recognize useful ideas, explain them later, and find the source again. This routine gives each of those jobs a small, deliberate step.',
    image: 'library-light', imageAlt: 'Podpin library for returning to podcast listening',
    sections: [
      { heading: 'Listen with one question in mind', paragraphs: ['Before an episode, ask what you hope to understand. “How does this person decide which projects to stop?” is easier to listen for than “Learn something about productivity.” A question gives you a reason to notice one passage over another.', 'You can still listen for enjoyment. Reserve this routine for episodes connected to something you want to learn, discuss, or do. Turning every conversation into homework is not necessary.'] },
      { heading: 'Capture a moment, then explain it from memory', paragraphs: ['When a passage seems relevant, save the moment when it is safe to do so. At the end of the session, put the transcript aside and try writing one sentence that answers your original question. Then return to the passage and correct anything you misremembered.', 'For example: “She stops a project when the next experiment cannot resolve the biggest uncertainty.” On review, you might discover that the speaker added an important exception. Add that exception to your note. The exercise exposes what you understood and what still needs checking.'], steps: ['Write the question you brought to the episode.', 'Save a passage that seems to answer it.', 'Explain the answer briefly without looking at the text.', 'Replay the source and repair gaps or mistakes.', 'Write one situation in which the idea might be useful.'] },
      { heading: 'Review when the idea has a job to do', paragraphs: ['A saved note becomes useful when you bring it into a real situation. Before a planning meeting, look at the decision-making examples you kept. Before writing an essay, revisit the passages connected to its question.', 'You can also choose a regular review time. Keep it small: a few highlights, one sentence of interpretation, and a decision to keep, clarify, or set aside each idea. This is a suggested habit, not a promise of a particular improvement in memory.'] },
      { heading: 'Use AI to find your way back, not to do the remembering', paragraphs: ['In Podpin, transcripts help you inspect wording, summaries orient you, and highlights with notes preserve the part you selected. Read an AI summary after your own first attempt if you want to compare what you noticed.', 'Do not confuse recognizing a polished summary with being able to explain its ideas. Ask yourself what the claim means, what example supports it, and what would make it unhelpful. If you cannot answer, return to the conversation rather than adding more highlights.'] }
    ],
    faq: [
      { q: 'How many highlights should I keep from a podcast?', a: 'There is no required number. Keep the passages that answer your question or change your understanding. One well-explained highlight can be more useful than a long list you never review.' },
      { q: 'Do I need to write notes during every episode?', a: 'No. Use focused note-taking for material you want to use later. Entertainment listening does not need a review system, and you can write your note after the episode when it is convenient.' }
    ],
    related: ['guides/take-podcast-notes', 'guides/podcast-learning-workflow', 'podcast-app-with-notes'], sources: [], updated: '2026-08-30'
  },
  {
    slug: 'guides/take-podcast-notes', locale: 'en', group: 'guides',
    title: 'How to Take Podcast Notes You Will Use | Podpin',
    heading: 'Write podcast notes that lead somewhere',
    description: 'Use a simple podcast note template to separate the speaker’s idea, your interpretation, and your next step without transcribing the whole episode.',
    intro: 'Good podcast notes do not repeat the whole conversation. They preserve a useful idea, its source, and your reason for keeping it. This three-part template helps you write a note you can act on later.',
    image: 'library-light', imageAlt: 'Podpin library in light mode',
    sections: [
      { heading: 'Separate the source, your thinking, and the next step', paragraphs: ['Start with the source idea: what did the speaker actually say? Then write your interpretation: why does it matter to your question? Finish with a next step: something to check, try, compare, or discuss.', 'This separation prevents a common problem: returning to a note and being unable to tell whether a sentence is a quotation, a paraphrase, or your own conclusion. Label direct quotations and verify their wording against the audio.'], bullets: ['Source: show, episode, speaker, and the relevant timestamp or saved moment.', 'Idea: a short paraphrase, or a clearly labeled and checked quotation.', 'My thinking: why I agree, disagree, or see a connection.', 'Next step: the smallest useful action or unresolved question.'] },
      { heading: 'A worked example', paragraphs: ['Imagine an episode about running better interviews. Your note could read: “Idea: ask about a recent real event before asking for general opinions. My thinking: our current questions invite broad answers. Next step: rewrite the first question to ask about the last time the problem happened.”', 'The example is intentionally short. It gives you a way to use the idea without pretending the podcast proved it will work in your setting. Keep the saved passage so you can recover the explanation and its limitations.'] },
      { heading: 'Capture lightly while listening; edit when you review', paragraphs: ['If writing interrupts the conversation, save the moment first and add your note later. In Podpin, highlights can carry personal notes and colors. Use a small color scheme if it helps you distinguish actions, questions, and references.', 'During review, remove vague reactions such as “great point.” Replace them with the specific claim or connection. If you cannot explain why you saved a passage, replay it. If it no longer matters, you do not have to turn it into a permanent note.'] },
      { heading: 'Do not mistake completeness for usefulness', paragraphs: ['A full transcript is valuable when you need the exact discussion. Your notes serve a different purpose: selecting and interpreting. Copying every paragraph into a personal archive makes the selection problem larger, not smaller.', 'Use episode summaries to orient yourself and transcripts to check detail. Keep your note focused on the work only you can do: explain the relationship to your own question. Before sharing a claim, verify important names, numbers, and references beyond an AI-generated summary.'] }
    ],
    faq: [
      { q: 'What should a podcast note include?', a: 'Keep enough source information to find the passage, a concise idea, your interpretation, and a next step or open question. Not every note needs all four as formal headings.' },
      { q: 'Should I copy the transcript into my notes?', a: 'Copy only a short passage when the wording itself matters, and mark it as a quotation. For most notes, a paraphrase plus a way back to the original moment is clearer.' }
    ],
    related: ['podcast-app-with-notes', 'guides/bookmark-podcast-moments', 'guides/remember-podcasts'], sources: [], updated: '2026-08-30'
  },
  {
    slug: 'guides/bookmark-podcast-moments', locale: 'en', group: 'guides',
    title: 'How to Bookmark Useful Podcast Moments | Podpin',
    heading: 'Save a podcast moment you can understand later',
    description: 'Learn what to bookmark in a podcast, how much context to keep, and how to turn a saved moment into a useful highlight instead of another forgotten pin.',
    intro: 'A podcast bookmark solves a location problem: where was that useful part? The best bookmarks also preserve enough context to explain why you saved them. Here is a simple way to choose and review those moments.',
    image: 'player', imageAlt: 'Podpin podcast player for listening and saving moments',
    sections: [
      { heading: 'Save the explanation, not only the punchline', paragraphs: ['A striking sentence can lose its meaning without the question that preceded it. When reviewing a bookmark, include enough context to identify the speaker’s claim, the example, and any qualification.', 'Suppose a guest says that a team should “slow down.” The useful part may be the explanation that follows: slow down a decision until one missing fact is known, not slow down all work. A bookmark that preserves only the phrase invites the wrong lesson.'] },
      { heading: 'Decide what earns a bookmark', paragraphs: ['Use a short selection rule. Save a passage if it answers a question you already have, challenges an assumption, contains an example you might use, or points to a source you want to inspect.', 'You do not need to save everything that sounds impressive. A bookmark library is easier to review when its entries have a reason to exist. If an episode is simply entertaining, enjoying it can be the whole point.'], bullets: ['Answer: this helps with a question I am working on.', 'Challenge: this conflicts with something I assumed.', 'Example: this makes a difficult idea easier to explain.', 'Reference: this names a source I want to investigate.'] },
      { heading: 'Turn a pin into a useful highlight', paragraphs: ['When it is safe to interact with your device, capture the moment using the app’s available controls. Later, return to it and add one sentence about its value. Podpin supports bookmarks, highlights with personal notes, and color-coded organization.', 'A note such as “An example of distinguishing an outcome from a metric” is more useful than “Good.” If you use colors, assign a few stable meanings instead of making a new category for every episode. This guide does not assume hands-free or headphone-triggered capture.'] },
      { heading: 'Review the context before sharing', paragraphs: ['Before using a saved passage in an article, meeting, or assignment, listen to it again. Check whether the speaker is presenting a personal opinion, recounting an anecdote, or describing a finding from another source.', 'If a transcript contains a compelling quotation, verify the words against the audio. Keep the show, episode, speaker, and timestamp in your working notes. A bookmark makes the source easier to recover; it does not make the source automatically reliable.'] }
    ],
    faq: [
      { q: 'What is the difference between a bookmark and a highlight?', a: 'A bookmark identifies a place to return to. A highlight often includes selected content and may carry a note or category. Apps use the labels differently; focus on whether you can recover the passage and your reason for saving it.' },
      { q: 'What if I cannot safely save a moment while listening?', a: 'Keep your attention on the activity that needs it. When you can stop safely, use a remembered phrase, topic, or approximate point in the episode to find the passage again.' }
    ],
    related: ['podcast-app-with-notes', 'guides/take-podcast-notes', 'search-podcast-transcripts'], sources: [], updated: '2026-08-30'
  },
  {
    slug: 'guides/find-a-podcast-quote', locale: 'en', group: 'guides',
    title: 'How to Find and Verify a Podcast Quote | Podpin',
    heading: 'Find the quote, then check what was actually said',
    description: 'A step-by-step method to recover a podcast quote using transcripts, alternative search terms, audio context, and clear source notes.',
    intro: 'Finding a remembered quote has two parts: locating the likely passage and confirming the words in context. A searchable transcript helps with the first. The original audio is essential for the second.',
    image: 'episode-detail', imageAlt: 'Podpin episode detail view',
    sections: [
      { heading: 'Start with the clues you actually have', paragraphs: ['Write down the likely show, guest, topic, and a distinctive word or phrase. Keep uncertain details labeled as uncertain. A confident but wrong memory of the guest can send you toward the wrong episode.', 'Search the likely transcript with a short phrase first. If that fails, try a less specific term, a synonym, or a word spoken near the quote. Speech recognition may miss a name while correctly capturing the surrounding discussion.'] },
      { heading: 'Use a recovery sequence', paragraphs: ['Avoid changing several assumptions at once. Start within the episode you think is correct, then broaden the search if the evidence points elsewhere. Podpin’s available transcripts can help you inspect and search episode text.', 'If a phrase appears more than once, review each plausible result. Introductions and recaps may mention the topic without containing the explanation you remember.'], steps: ['Identify the most likely episode from show, guest, and topic clues.', 'Search for a distinctive phrase or a shorter keyword.', 'Try nearby terms or alternative wording when no match appears.', 'Read the sentences before and after a promising match.', 'Replay the passage and check the speaker and exact wording.', 'Record the source and save the moment for later verification.'] },
      { heading: 'Keep quotation and paraphrase separate', paragraphs: ['A quotation uses the speaker’s words. A paraphrase uses your own wording to describe the idea. Do not place a remembered or AI-rewritten sentence in quotation marks because it captures roughly what you think was said.', 'For example, your memory might say “Teams move faster when decisions are reversible.” The actual passage may discuss only a particular kind of decision. Either quote the verified wording with its qualification, or write a careful paraphrase that preserves the narrower meaning.'] },
      { heading: 'Record enough information for someone else to find it', paragraphs: ['Keep the show title, episode title, publication date when available, speaker, and timestamp. Add the episode’s source link to your own research notes if you have it. Timestamps can shift when versions or inserted advertisements differ, so a short contextual description is helpful too.', 'When the quote refers to a study, book, or news event, investigate that reference independently. The fact that you accurately found the quotation establishes what was said, not whether the underlying claim is true. Generated summaries and reference lists should be treated as leads to check.'] }
    ],
    faq: [
      { q: 'Can I quote directly from an AI transcript?', a: 'Verify the passage against the audio first. AI transcripts can mishear words, names, and numbers. Mark your own rewritten version as a paraphrase rather than a direct quotation.' },
      { q: 'What if I remember the meaning but not the words?', a: 'Search for topic terms, examples, or related phrases. Once you locate a likely section, listen again. If you cannot verify the wording, do not present your memory as an exact quote.' }
    ],
    related: ['search-podcast-transcripts', 'guides/transcripts-summaries-highlights', 'guides/podcasts-for-students'], sources: [], updated: '2026-08-30'
  },
  {
    slug: 'guides/transcripts-summaries-highlights', locale: 'en', group: 'guides',
    title: 'Podcast Transcripts vs Summaries vs Highlights | Podpin',
    heading: 'Use the right view of a podcast for the job',
    description: 'Understand the difference between podcast transcripts, summaries, chapters, and highlights, and when to use each in your listening workflow.',
    intro: 'A transcript, a summary, and a highlight can all describe the same episode, but they answer different questions. Knowing the difference helps you choose the right tool without expecting one to do everything.',
    image: 'episode-detail', imageAlt: 'Podpin episode detail interface',
    sections: [
      { heading: 'The short version', paragraphs: ['A transcript helps answer “What was said?” A summary helps answer “What is this about?” A highlight helps answer “What do I want to keep?” Chapters add a map of the conversation.', 'These views work together. None guarantees that the speaker is correct, and generated text can introduce its own mistakes. Return to the audio when wording, nuance, or attribution matters.'], table: { headers: ['View', 'Best use', 'Main limitation'], rows: [['Transcript', 'Search and inspect wording', 'Speech recognition can make errors'], ['Summary', 'Get oriented or refresh the broad topic', 'Condenses and omits detail'], ['Chapters', 'Navigate the conversation’s structure', 'Headings are not the complete argument'], ['Highlight with a note', 'Keep a selected idea and your interpretation', 'Reflects your selection, not the whole episode']] } },
      { heading: 'Use a transcript when precision matters', paragraphs: ['If you need to find a name, distinguish two terms, or inspect an explanation, start with the transcript. Read the surrounding exchange and replay it before using the wording as a quotation.', 'A transcript is longer because its job is to preserve speech rather than select the most useful ideas. That can make it a poor first choice when you only want to decide whether an episode fits today’s question.'] },
      { heading: 'Use summaries and chapters to get your bearings', paragraphs: ['An episode summary provides an overview. Chapters break the conversation into navigable parts. Use them to spot a relevant discussion or refresh your memory before a deeper review.', 'Do not treat a missing point in a summary as proof it was never discussed. Summarization selects and compresses. It may remove the example, uncertainty, or exception that makes a claim understandable. Generated references also need checking before they become sources in your work.'] },
      { heading: 'Use a highlight to make a personal selection', paragraphs: ['A highlight becomes most useful when paired with your reason for saving it. “This example explains the tradeoff in our project” tells you something that even a good general summary cannot know.', 'In Podpin, you can work with transcripts, summaries, insights, chapters, and highlights with notes and colors. A practical sequence is to get oriented, inspect one relevant passage, and keep the part that matters to you. Transcription runs on-device; optional cloud AI and available local AI modes should be considered separately when choosing your processing preferences.'] },
      { heading: 'An example workflow', paragraphs: ['For an interview about creative work, read the summary to locate the section on feedback. Use the chapter structure and transcript to recover the example. Replay the explanation, then save a highlight with a note about the feedback conversation you are preparing for. Each view has done a distinct job.'] }
    ],
    faq: [
      { q: 'Can a summary replace listening to the episode?', a: 'It can help you decide whether to listen or refresh broad themes. It cannot preserve every example, qualification, and exchange. Listen to the relevant passage before relying on a detailed claim.' },
      { q: 'Are my highlights more accurate than an AI summary?', a: 'Not automatically. A highlight reflects what you selected and may use generated transcript text. Verify it against the audio and distinguish the source claim from your interpretation.' }
    ],
    related: ['ai-podcast-player', 'on-device-podcast-transcription', 'podcast-app-with-notes'], sources: [], updated: '2026-08-30'
  },
  {
    slug: 'guides/podcast-learning-workflow', locale: 'en', group: 'guides',
    title: 'A Practical Podcast Learning Workflow | Podpin',
    heading: 'Turn a podcast into one useful next step',
    description: 'A focused podcast learning workflow for choosing an episode, capturing an idea, checking the source, and applying what you learned.',
    intro: 'A growing queue is not the same as a learning plan. Start with a real question, choose an episode that might help, and finish with a small output: a clearer explanation, a source to inspect, or an action to try.',
    image: 'library-dark', imageAlt: 'Podpin podcast library in dark mode',
    sections: [
      { heading: 'Choose the output before the episode', paragraphs: ['Decide what you want to leave with. If you are learning a concept, your output might be a short explanation in your own words. If you are exploring a decision, it might be a list of tradeoffs and unanswered questions.', 'For example: “I want to explain when a prototype is useful and when it is misleading.” That question gives you a filter for choosing an episode and deciding which passages deserve a highlight.'] },
      { heading: 'Use a five-stage loop', paragraphs: ['The sequence below is a working template, not a timed productivity challenge. Spend more attention on difficult material and skip annotation when the purpose is simply enjoyment.'], steps: ['Choose: pick an episode connected to one specific question.', 'Listen: follow the argument and save relevant moments when convenient.', 'Explain: write the main idea in your own words before checking the summary.', 'Verify: replay key passages and investigate important references.', 'Use: make one small output connected to the original question.'] },
      { heading: 'Give each tool a clear role', paragraphs: ['Use a summary to see the broad outline. Use chapters to locate a section. Use transcript search to recover wording. Use highlights and personal notes to preserve your judgment. Podpin brings those tools into the podcast experience.', 'Do not collect generated material merely because it is available. If a full transcript does not help today’s question, you may only need one passage. If a summary leaves a claim unclear, go deeper instead of asking the overview to carry more detail than it contains.'] },
      { heading: 'Close the loop with something visible', paragraphs: ['An output can be modest: three sentences explaining a concept, one revised interview question, or a note comparing two speakers’ assumptions. The point is to make your understanding inspectable rather than leave it as a feeling that an episode was useful.', 'If you want to try an idea, record the situation in which you will try it and what you will look for. A podcast example may not transfer to your circumstances. Keep the experiment small enough to revise when reality disagrees.'] },
      { heading: 'Review the system, not just the saved material', paragraphs: ['After a few episodes, ask whether your notes helped you find and use anything. If not, reduce the number of highlights, make your questions more specific, or add clearer source details.', 'Podpin’s Apple-device apps and optional CloudKit sync can support listening and later review in different settings. Check your plan, device compatibility, and sync configuration before relying on that routine. The workflow matters more than using every available feature.'] }
    ],
    faq: [
      { q: 'How long should a podcast review take?', a: 'There is no fixed duration. Review enough to explain the useful idea and identify the next step. Complex or consequential claims deserve more checking than a casual example.' },
      { q: 'Can I use this workflow without Podpin?', a: 'Yes. You need a way to find the original passage and keep a short note. Podpin combines several parts of the workflow, but the method does not depend on a particular app.' }
    ],
    related: ['guides/remember-podcasts', 'guides/take-podcast-notes', 'podcast-app-for-mac'], sources: [], updated: '2026-08-30'
  },
  {
    slug: 'guides/podcasts-for-students', locale: 'en', group: 'guides',
    title: 'How to Use Podcasts for Studying and Research | Podpin',
    heading: 'Use podcasts as a starting point for study',
    description: 'A student workflow for connecting podcasts to course questions, taking source-aware notes, checking quotations, and following references.',
    intro: 'Podcasts can introduce an argument, make a topic more approachable, or point you toward useful sources. For study, the important step is connecting the conversation to a specific question and checking what supports it.',
    image: 'episode-detail', imageAlt: 'Podpin episode view for reviewing podcast material',
    sections: [
      { heading: 'Bring a course question to the episode', paragraphs: ['Start with a concept from your class, reading, or assignment. Ask how the episode might help: does it offer an example, explain a disagreement, or introduce a primary source? This keeps listening connected to the work you actually need to do.', 'For example, if you are studying how historians interpret evidence, listen for how a guest distinguishes an established fact from a disputed interpretation. Your note can compare that distinction with a reading from class.'] },
      { heading: 'Keep source claims separate from your response', paragraphs: ['Use two short parts in your note: “The speaker argues…” and “My question or connection…” Add the episode, speaker, and timestamp so you can recover the passage. If the speaker mentions a study, record it as a reference to investigate, not a verified finding.', 'Podpin’s transcripts, highlights, and personal notes can help you keep that context together. Search and summaries are useful navigation aids, but their generated text should not be treated as an authoritative version of the source.'], bullets: ['Claim: what is being argued?', 'Support: what example or evidence is offered?', 'Connection: how does this relate to the course material?', 'Question: what remains uncertain or disputed?', 'Source: where can I find the passage and its references?'] },
      { heading: 'Check quotations and follow the evidence', paragraphs: ['Replay any passage you intend to quote. Confirm the exact words, who said them, and whether the surrounding exchange qualifies the claim. A transcript can contain a small recognition error that changes the meaning.', 'When a guest cites a book, paper, or dataset, look for the original material and read the relevant section. An interview about research and the research itself play different roles. Follow your instructor’s requirements for acceptable sources, citation style, and disclosure of AI assistance.'] },
      { heading: 'Make a study output you can test', paragraphs: ['Close the episode and explain the idea in a short paragraph, outline an argument, or write a question you would ask in class. Then compare your output with the source. Where did you oversimplify? Which term could you not define?', 'A useful final note might say: “This interview gives an example of the debate, but I still need the original article to evaluate the evidence.” That is a productive result. Learning from a podcast does not require treating every episode as a source you will cite.'] }
    ],
    faq: [
      { q: 'Can I cite a podcast in an assignment?', a: 'Check your instructor’s source requirements and the required citation style. If you use an episode, keep the show, episode title, publication details, speaker where relevant, and a timestamp for the passage.' },
      { q: 'Should I use an AI summary as my study notes?', a: 'Use it to get oriented or compare with your own understanding. Write your own explanation, verify important details, and follow any course rules about AI use.' }
    ],
    related: ['guides/find-a-podcast-quote', 'guides/take-podcast-notes', 'guides/transcripts-summaries-highlights'], sources: [], updated: '2026-08-30'
  },
  {
    slug: 'guides/choose-ai-podcast-app', locale: 'en', group: 'guides',
    title: 'How to Choose an AI Podcast App | Podpin',
    heading: 'Choose an AI podcast app around your actual workflow',
    description: 'Evaluate AI podcast apps by transcription, note capture, privacy modes, device support, integrations, and real episode checks—not feature counts.',
    intro: 'The right AI podcast app depends on what you want to do after pressing play. A listener who needs headphone capture has different requirements from someone who wants local transcription or a Mac review workflow.',
    image: 'player', imageAlt: 'Podpin podcast listening interface',
    sections: [
      { heading: 'Name the job before comparing features', paragraphs: ['Choose your most important outcome: find a forgotten passage, save ideas during a walk, study a technical episode, or send notes into an existing knowledge system. Write down any non-negotiable device or accessibility needs too.', 'Then rank the requirements. An impressive chat feature will not solve a missing export integration, and a strong transcript does not tell you whether capturing a moment feels convenient. Evaluate the whole path from listening to using the idea.'] },
      { heading: 'Ask specific questions about AI and privacy', paragraphs: ['“AI-powered” does not say where processing happens. Ask separately about transcription, summaries, chat, synchronization, and analytics. Read current privacy disclosures and inspect the controls available in the app.', 'Podpin offers on-device transcription and a choice of local or optional cloud AI for supported summarization workflows. Choose on-device AI mode if local processing is your priority; do not assume the word “private” covers every mode or network activity. Optional CloudKit sync is separate and may depend on your plan.'], bullets: ['Does my device support the AI features I need?', 'Which models or audio must be downloaded first?', 'Can I choose where supported AI processing runs?', 'What works without a connection after setup?', 'What is synchronized, and what do privacy disclosures say?'] },
      { heading: 'Run the same small test in each candidate', paragraphs: ['Choose one representative episode: the kind of recording, speakers, and topic you normally hear. Check whether you can find a specific explanation, inspect its transcript, save a moment, and understand the note later.', 'If you need exports, headphones, a particular language, or several devices, test that exact path. Do not infer support from a similar-looking screenshot. This is an evaluation checklist for you to run, not a claim that we have conducted hands-on tests of every app.'], steps: ['Play a representative episode and check the listening controls.', 'Find one known passage in the available transcript.', 'Save a useful moment with your own interpretation.', 'Review it later on the device you actually use for notes.', 'Check current pricing, limits, compatibility, and privacy settings.'] },
      { heading: 'Accept a tradeoff you can explain', paragraphs: ['You may prefer a focused Apple-device app with local transcription, or a service with integrations and capture methods that fit your existing routine. Neither choice is established by counting the number of features on a landing page.', 'Podpin is worth considering for transcripts, highlights with notes and colors, and an Apple-device workflow. If third-party exports or hands-free capture are essential, verify those requirements directly rather than assuming they are included. Review current product documentation before committing to a migration.'] }
    ],
    faq: [
      { q: 'What is the best AI podcast app?', a: 'There is no universal answer. Match the app to your capture method, review habits, devices, privacy preferences, and required integrations, then test a real episode before deciding.' },
      { q: 'Should I compare subscription prices alone?', a: 'No. Check which features and usage limits belong to each plan, the pricing in your region, and whether the app supports your actual workflow. A lower price does not help if a required capability is missing.' }
    ],
    related: ['compare/podpin-vs-snipd', 'compare/podpin-vs-apple-podcasts', 'private-ai-podcast-player'], sources: [appStore], updated: '2026-08-30'
  },
  {
    slug: 'compare/podpin-vs-snipd', locale: 'en', group: 'compare',
    title: 'Podpin vs Snipd: Podcast Notes and AI Workflows',
    heading: 'Podpin vs Snipd: choose the workflow you will use',
    description: 'Compare Podpin and Snipd for podcast notes, AI processing, capture methods, and integrations using published product information, not invented tests.',
    intro: 'Podpin and Snipd both help listeners return to useful podcast ideas. The meaningful choice is about how you capture a moment, where AI processing happens, and what you want to do with the note afterward.',
    image: 'library-light', imageAlt: 'Podpin library interface',
    sections: [
      { heading: 'What this comparison is based on', paragraphs: ['This is a documentation-based comparison reviewed on August 30, 2026. It uses Podpin’s current product information and the official Snipd pages linked below. It is not a hands-on benchmark, transcript-accuracy test, or claim that one app is best for every listener.', 'Prices, plan limits, and supported features can change. Verify the current listing and your exact workflow before moving a listening library or choosing a subscription. We do not score performance, battery life, or accuracy without comparable testing.'] },
      { heading: 'The main differences to investigate', paragraphs: ['Podpin combines on-device transcription with highlights, personal notes, and colors on Apple devices. Supported summarization workflows offer local AI and an optional cloud mode. Optional CloudKit sync depends on your plan and setup.', 'Snipd’s official product page emphasizes headphone-triggered capture, podcast chat, and sending highlights into other note-taking tools. Those are meaningful strengths if you want to capture without opening the screen or already organize your knowledge elsewhere.'], table: { headers: ['Your priority', 'Podpin', 'Snipd'], rows: [['AI processing choice', 'On-device transcription; local and optional cloud summary modes', 'Check current AI processing and privacy documentation'], ['Keeping personal takeaways', 'Highlights with notes and colors', 'AI snips with audio, transcript, and summary'], ['Capture with headphones', 'Not a feature promised in this comparison', 'Officially advertised'], ['External notes workflow', 'Do not assume third-party export integrations', 'Advertises note-app sync and Markdown export']] } },
      { heading: 'When Podpin may fit better', paragraphs: ['Consider Podpin when you want an Apple-device listening and review routine, on-device transcription, and the option to choose local AI for supported summaries. A useful test is whether you can find a passage, save a highlight, and add the reason it matters without making your workflow more complicated.', 'Local processing does not mean every feature is offline or no data is collected. Review current privacy disclosures, select your AI mode intentionally, and treat CloudKit sync as a separate choice. Confirm model and device requirements before depending on local AI.'] },
      { heading: 'When Snipd may fit better', paragraphs: ['Snipd advertises integrations with tools including Notion, Readwise, and Obsidian, alongside Markdown export. It also offers podcast chat and audio or YouTube import features. If those are central to your routine, evaluate them directly rather than assuming Podpin is an equivalent replacement.', 'Snipd’s pricing page distinguishes free and premium AI access and describes processing limits. Check the current limits and your regional price. Feature availability matters more than comparing a headline subscription number without knowing what it includes.'] },
      { heading: 'Make the decision with one real episode', paragraphs: ['Choose an episode you know well and a specific passage to recover. Compare capture, review, and the final destination of your note. If possible, repeat the review the next day: can you understand why the moment was saved? That is a more relevant personal test than a generic winner badge.'] }
    ],
    faq: [
      { q: 'Is Podpin a direct replacement for every Snipd feature?', a: 'No. Do not assume parity in headphone capture, chat, imports, or external note integrations. Podpin’s documented strengths here are its Apple-device workflow, on-device transcription, AI processing choices, and highlights with notes.' },
      { q: 'Does this comparison establish which app is more private?', a: 'No blanket privacy ranking is made. Compare processing modes, synchronization, collection disclosures, and your settings feature by feature. Local transcription is one part of that evaluation, not the entire answer.' }
    ],
    related: ['guides/choose-ai-podcast-app', 'private-ai-podcast-player', 'podcast-app-with-notes'],
    sources: [appStore, { label: 'Snipd — official product features', url: 'https://www.snipd.com/' }, { label: 'Snipd — current plans and processing limits', url: 'https://www.snipd.com/pricing' }], updated: '2026-08-30'
  },
  {
    slug: 'compare/podpin-vs-apple-podcasts', locale: 'en', group: 'compare',
    title: 'Podpin vs Apple Podcasts: Transcripts and Notes',
    heading: 'Podpin vs Apple Podcasts: what happens after listening?',
    description: 'Compare Podpin and Apple Podcasts for transcripts, saving personal takeaways, Apple-device listening, and review using current official documentation.',
    intro: 'Apple Podcasts already offers useful transcript and listening tools. Podpin is worth considering when you want highlights with personal notes and colors, AI summaries, and an explicit on-device transcription workflow.',
    image: 'player', imageAlt: 'Podpin podcast player interface',
    sections: [
      { heading: 'A documented comparison, not a winner by default', paragraphs: ['This comparison was reviewed on August 30, 2026 using Podpin product information and official Apple support documentation. It does not claim hands-on performance testing or rank transcript accuracy, speed, or reliability.', 'Start with the app you already use and identify the missing job. If you only need to listen and occasionally search a transcript, a switch may not solve a meaningful problem. If you want to keep your own interpretations attached to selected moments, compare that workflow specifically.'] },
      { heading: 'Apple Podcasts already does more than playback', paragraphs: ['Apple documents time-synced transcripts, searching within transcript text, and jumping to a selected passage on iPhone and iPad. Its guide also describes text selection and sharing, chapters, and links to mentioned content. Availability varies by episode and region.', 'On Mac, Apple documents transcript reading and search, including options for whole-word and case matching. It also supports sharing an episode from a selected transcript position. It would be inaccurate to present transcript search as unique to Podpin.'], table: { headers: ['Need', 'Podpin', 'Apple Podcasts'], rows: [['Listen to podcasts', 'Podcast playback on Apple devices', 'Podcast playback and library tools'], ['Read and search episode text', 'On-device generated transcripts and search', 'Supported for available transcripts'], ['Keep your interpretation', 'Highlights with personal notes and colors', 'Assess whether transcript selection and sharing meet your needs'], ['AI workflow choice', 'Local and optional cloud modes for supported summaries', 'Consult current Apple documentation for available features']] } },
      { heading: 'Where Podpin focuses the workflow', paragraphs: ['Podpin combines listening with on-device transcription, summaries, insights, chapters, references, and highlights you can annotate. The practical difference is not merely seeing text; it is keeping the passage and your reason for saving it together.', 'For example, after hearing an interview technique, you can save the moment and add a note about the question you want to rewrite. Colors can distinguish an action from a reference or an unresolved question. These are organizational choices for your own learning, not claims that AI validates the episode.'] },
      { heading: 'Check requirements before switching', paragraphs: ['Podpin’s local transcription and supported AI features depend on compatible devices, software, models, and setup. Optional cloud AI is a separate processing mode, and optional CloudKit sync depends on your plan and configuration. Check the current App Store information for your devices.', 'Also verify that your essential shows and subscription arrangements fit any proposed move. Do not assume purchases, saved items, or listening history transfer between apps. A documentation comparison is not evidence of migration support.'] },
      { heading: 'Try the same review task', paragraphs: ['Choose a familiar episode and find one important explanation. Check the words, save the source in the way each app allows, and write why it matters. Review it later. If your existing Apple Podcasts workflow already does what you need, keeping it is reasonable. Consider Podpin when its personal-note and AI workflow addresses a concrete gap.'] }
    ],
    faq: [
      { q: 'Does Apple Podcasts have searchable transcripts?', a: 'Yes. Apple documents transcript search on iPhone, iPad, and Mac where transcripts are available. Availability is not guaranteed for every episode, language, or region.' },
      { q: 'Why consider Podpin if Apple Podcasts already has transcripts?', a: 'Consider Podpin for the combination of highlights with personal notes and colors, AI summaries, and on-device transcription with processing choices for supported AI workflows. Evaluate those jobs rather than assuming transcript access alone requires a different app.' }
    ],
    related: ['guides/choose-ai-podcast-app', 'podcast-app-with-notes', 'podcast-app-for-mac'],
    sources: [appStore, { label: 'Apple Support — playback and transcripts on iPhone and iPad', url: 'https://support.apple.com/en-us/118668' }, { label: 'Apple Support — episode transcripts on Mac', url: 'https://support.apple.com/guide/podcasts/read-along-with-episode-transcripts-pode3855ee98/mac' }], updated: '2026-08-30'
  }
];
