const app = 'https://apps.apple.com/us/app/ai-podcast-player-podpin/id6760191862';
const policy = 'https://recondite-muenster-de4.notion.site/Privacy-Policy-Podpin-31f34bbaf0bc80f9a4dbcdc5e5dc6f91';
const support = 'https://recondite-muenster-de4.notion.site/Frequent-Questions-Podpin-31f34bbaf0bc8092aba8d66866d0a2f5';
const base = { locale: 'en', group: 'trust', updated: '2026-08-30', faq: [] };
export default [
  { ...base, slug: 'about', title: 'About Podpin | A podcast player for curious listeners', heading: 'A place for the ideas you hear.', description: 'Meet Podpin, the Apple-platform podcast player by Antonio Jose Martinez Sanchez, built around transcripts, highlights, notes, and revisiting useful ideas.', intro: 'Podpin helps curious listeners turn a conversation into something they can find again. Listening is the beginning; keeping the useful idea is the next step.', sections: [
    { heading: 'From listening to remembering', paragraphs: ['An hour-long episode can contain one sentence you want to keep. Podpin puts playback, transcripts, and timestamped highlights together so that sentence does not have to disappear into your listening history. Add your own note, keep the source, and return when the idea becomes useful.', 'The app is built for iPhone, iPad, and Mac, with companion experiences on supported Apple devices. It combines on-device transcription with AI-assisted summaries and episode structure. AI availability depends on your hardware, language, selected processing mode, and configuration.'] },
    { heading: 'Made by an independent developer', paragraphs: ['Podpin is developed by Antonio Jose Martinez Sanchez, the developer identified on its App Store listing. The website and learning guides are published by Podpin. Comparisons disclose their sources and are not independent third-party reviews.', 'For verified compatibility, current availability, and purchase information, use the App Store listing. For product questions, start with our support page.'] },
  ], related: ['ai-podcast-player', 'support', 'editorial'], sources: [{ label: 'Podpin on the App Store', url: app }, { label: 'Antonio J. Martinez — developer portfolio', url: 'https://www.antoniojmartinez.com/apps.html' }] },
  { ...base, slug: 'compatibility', title: 'Podpin compatibility | iPhone, iPad, Mac and Watch', heading: 'Check your device before you download.', description: 'Podpin requirements for iPhone, iPad, Apple silicon Mac, and Apple Watch. Understand why app compatibility and AI feature availability are different.', intro: 'Being able to install Podpin and being able to use every AI feature are different checks. Start with the operating system, then check the selected transcription and AI models.', sections: [
    { heading: 'App Store device requirements', paragraphs: ['The App Store listing checked on August 30, 2026 lists the following minimum requirements. The store remains the source of truth if these change.'], table: { headers: ['Device', 'Minimum requirement'], rows: [['iPhone', 'iOS 26.0 or later'], ['iPad', 'iPadOS 26.0 or later'], ['Mac', 'macOS 26.0 or later; Apple M1 chip or later'], ['Apple Watch', 'watchOS 11.6 or later']] } },
    { heading: 'AI has additional requirements', paragraphs: ['On-device transcription depends on supported speech models and languages. AI summaries and related features depend on the chosen provider, device capabilities, and model availability. Some models require an initial download; a supported operating system alone does not guarantee every AI feature.', 'Podpin offers a local AI mode and may offer optional cloud AI when configured. Cloud processing requires connectivity. App interface languages should not be treated as a list of supported transcription or summarization languages.'] },
    { heading: 'Cross-device listening', paragraphs: ['CloudKit sync is optional and can depend on your plan and settings. It uses a network connection and the Apple account configured on your devices. Companion Watch and CarPlay experiences do not imply that every transcript or AI operation runs on those surfaces.', 'The website explains Podpin; it is not a browser-based podcast player. There is no Android version advertised here.'] },
  ], related: ['podcast-app-for-iphone', 'podcast-app-for-mac', 'support'], sources: [{ label: 'Current Podpin compatibility on the App Store', url: app }] },
  { ...base, slug: 'privacy', title: 'Podpin privacy | On-device, cloud AI and sync explained', heading: 'Know where the processing happens.', description: 'Understand Podpin’s on-device transcription, optional cloud AI, CloudKit sync, and App Store privacy disclosures. Read the official app privacy policy.', intro: 'On-device transcription is not the same promise as “nothing ever leaves your device.” This overview separates transcription, AI processing, sync, and analytics.', sections: [
    { heading: 'Transcription and AI are separate choices', paragraphs: ['Podpin supports audio transcription on the device. Summaries, chapters, insights, and related AI output depend on the selected AI mode. In local mode, supported providers run on the device. Optional cloud AI uses a remote provider when available and selected.', 'Check the current app settings before processing sensitive material. Downloads, podcast directory requests, and audio streaming need network access. Device-side processing can also require a model download before use.'] },
    { heading: 'Sync and app diagnostics', paragraphs: ['Optional CloudKit sync moves supported library data between your Apple devices. Its availability depends on your plan and settings. Local AI and cross-device sync are separate controls.', 'The current App Store privacy label declares usage data and diagnostics that may be collected and are not linked to identity. This website does not describe the app as tracking-free. Read the full developer policy and Apple’s current disclosures for details rather than relying on this short overview.'] },
    { heading: 'Website measurement', paragraphs: ['The website works without analytics. If Google Analytics is configured for a production deployment, it is loaded only after you explicitly accept optional analytics. You can change your choice using the analytics settings control in the footer. Without a configured analytics service, no such prompt is shown.', 'Optional website events measure page views and App Store link clicks, not app installations. Event payloads exclude query strings and URL fragments. No podcast audio, transcript, or note content is collected by this website. Ordinary hosting access logs and services reached through external links have their own privacy practices.'] },
    { heading: 'Read the full app policy', paragraphs: ['This page is a product-processing overview, not a replacement for the developer’s full privacy policy. The official app policy remains at the link below while its legal text is reviewed for an on-domain migration. For privacy questions, follow the support route in that policy.'] },
  ], related: ['private-ai-podcast-player', 'support', 'compatibility'], sources: [{ label: 'Official Podpin app privacy policy', url: policy }, { label: 'App Store privacy disclosures', url: app }] },
  { ...base, slug: 'support', title: 'Podpin support | Transcripts, highlights and sync help', heading: 'Get back to the moment that matters.', description: 'Troubleshoot Podpin transcripts, AI availability, highlights, playback, and cross-device sync. Find the official support resource and device requirements.', intro: 'Start with the task that is not working. A little information about the episode, device, and selected processing mode makes a support request much more useful.', sections: [
    { heading: 'A transcript is missing or incomplete', steps: ['Check that the episode audio is available and that your selected transcription engine supports the language.', 'Allow required speech models to finish downloading and check available device storage.', 'If a transcript exists, search a short distinctive word rather than a whole remembered sentence. Recognition may differ from the original speech.', 'When reporting a problem, include the episode link, timestamp, device model, operating-system version, and app version. Do not send private audio or notes unless necessary and requested.'], paragraphs: [] },
    { heading: 'AI output is unavailable', paragraphs: ['Check the AI mode selected in settings. Local AI depends on model and device availability; optional cloud AI requires a network connection and an available provider. An app-interface language being available does not guarantee AI support for that language.', 'A generated summary is an aid, not a verified record. Compare names, quotes, and important claims with the original audio.'] },
    { heading: 'My library is not syncing', paragraphs: ['Check whether your plan includes sync, whether CloudKit sync is enabled, and whether both devices use the expected Apple account. Make sure both devices have network access and a supported app version.', 'Do not delete local data as a first troubleshooting step. Keep the device with the expected library intact and describe which items differ between devices.'] },
    { heading: 'Official help', paragraphs: ['Open the Podpin help resource linked below for current support information. The developer’s privacy policy includes the route for privacy-related questions. This website does not submit a ticket or collect your private listening data.'] },
  ], related: ['compatibility', 'privacy', 'guides/find-a-podcast-quote'], sources: [{ label: 'Official Podpin help and frequently asked questions', url: support }, { label: 'App Store listing', url: app }, { label: 'Privacy policy and privacy contact', url: policy }] },
  { ...base, slug: 'pricing', title: 'Podpin pricing and availability | Check the App Store', heading: 'Check the offer for your device and region.', description: 'Find current Podpin download availability and purchase terms on the App Store. Check feature requirements and optional sync before choosing a plan.', intro: 'The App Store and the app’s purchase screen show the offer available to you. This page does not promise that every feature is free or available on every device.', sections: [
    { heading: 'Download and purchase information', paragraphs: ['The public listing checked on August 30, 2026 presents Podpin as free to download. That does not establish free access to every feature forever. Features, trials, plans, and regional availability can change; inspect the current store listing and any in-app purchase screen before confirming a purchase.', 'No fixed subscription price is published here because it has not been verified across storefronts. Optional CloudKit sync and other capabilities may depend on your plan.'] },
    { heading: 'Choose for your workflow', bullets: ['Check device and AI-model compatibility before installing.', 'Try a familiar episode so you can judge transcript usefulness against the original audio.', 'Check which AI processing mode is active and what requires an internet connection.', 'Read the price, renewal period, trial terms, and feature access shown before confirming any purchase.'], paragraphs: [] },
  ], related: ['compatibility', 'ai-podcast-player', 'support'], sources: [{ label: 'Current Podpin offer on the App Store', url: app }] },
  { ...base, slug: 'editorial', title: 'Podpin editorial standards | Sources and comparisons', heading: 'Useful guidance, with its limits visible.', description: 'How Podpin writes learning guides and product comparisons: primary sources, clear disclosures, accurate product claims, and no invented tests or ratings.', intro: 'Podpin publishes these guides to help you listen, capture, and revisit ideas. We are the maker of the app, not an independent review publication.', sections: [
    { heading: 'Guides and examples', paragraphs: ['The workflows are practical suggestions, not promises of improved memory or academic performance. Examples are illustrative unless explicitly identified otherwise. AI assistance was used to draft and translate this launch content; product descriptions were checked against the available app implementation and public listing.', 'Screenshots are from Podpin. An iPhone screenshot is not evidence of a Mac-specific interface or proof that every feature is available on every device. Always check the compatibility page and current app settings.'] },
    { heading: 'Comparison method', paragraphs: ['Comparison pages use linked product documentation and public listings, checked on the date shown. They do not claim hands-on testing, measured accuracy, battery benchmarks, or an independent ranking. Competitors’ strengths and relevant tradeoffs are included.', 'Prices, platform coverage, features, and processing choices may change. Use the linked source to verify a detail before switching apps. No invented star ratings, testimonials, or retention statistics are used.'] },
    { heading: 'Corrections and updates', paragraphs: ['For a correction, use the official support route and include the page URL and the specific claim. Product claims, compatibility information, and comparisons should be reviewed after material releases, with the displayed update date changed only when the content is actually reviewed or revised.'] },
  ], related: ['about', 'compare/podpin-vs-snipd', 'support'], sources: [{ label: 'Official Podpin support', url: support }] },
  { ...base, slug: 'terms', title: 'Podpin app terms | Where to find the applicable licence', heading: 'Read the terms that apply to your download.', description: 'Find Podpin’s current App Store listing and applicable app licence. This page links to the terms rather than inventing a new agreement.', intro: 'The licence and purchase terms presented by the App Store govern the app you download. This page is a directory to those documents, not a new contract.', sections: [
    { heading: 'App licence', paragraphs: ['Use the licence agreement linked from Podpin’s current App Store listing. Apple’s Standard EULA applies where a custom agreement is not provided. A reference to Apple’s standard agreement here does not replace any specific agreement shown by the store.'] },
    { heading: 'Podcast content and generated output', paragraphs: ['The podcasts you listen to belong to their respective creators and rights holders. Access to a feed does not automatically grant permission to republish a full transcript or audio recording.', 'Check generated transcripts and summaries against the original recording before using a quote or relying on an important claim. Our guides are general product guidance, not professional advice.'] },
  ], related: ['privacy', 'support', 'pricing'], sources: [{ label: 'Podpin listing and licence agreement', url: app }, { label: 'Apple Standard EULA', url: 'https://www.apple.com/legal/internet-services/itunes/dev/stdeula/' }] },
];
