export default {
  en: {
    skip: 'Skip',
    menu: 'Menu',
    download: 'Download',
    features: 'Features',
    guides: 'Guides',
    compare: 'Compare',
    about: 'About',
    support: 'Support',
    privacy: 'Privacy',
    compatibility: 'Compatibility',
    pricing: 'Pricing',
    related: 'Related',
    faq: 'FAQ',
    contents: 'Contents',
    sourceHeading: 'Sources',
    updated: 'Updated',
    language: 'Language',
    home: 'Home',
    backHome: 'Back to home',
    readGuide: 'Read the guide',
    allGuides: 'All guides',
    learnMore: 'Learn more',
    footerTagline: 'Listen. Learn. Remember.',
    copyLink: 'Copy link',
    linkCopied: 'Link copied',
  },
  es: {
    skip: 'Saltar',
    menu: 'Menú',
    download: 'Descargar',
    features: 'Funciones',
    guides: 'Guías',
    compare: 'Comparar',
    about: 'Acerca de',
    support: 'Soporte',
    privacy: 'Privacidad',
    compatibility: 'Compatibilidad',
    pricing: 'Precios',
    related: 'También te puede interesar',
    faq: 'Preguntas frecuentes',
    contents: 'Contenido',
    sourceHeading: 'Fuentes',
    updated: 'Actualizado',
    language: 'Idioma',
    home: 'Inicio',
    backHome: 'Volver al inicio',
    readGuide: 'Leer la guía',
    allGuides: 'Todas las guías',
    learnMore: 'Más información',
    footerTagline: 'Escucha. Aprende. Recuerda.',
    copyLink: 'Copiar enlace',
    linkCopied: 'Enlace copiado',
  },
  fr: {
    skip: 'Passer',
    menu: 'Menu',
    download: 'Télécharger',
    features: 'Fonctionnalités',
    guides: 'Guides',
    compare: 'Comparer',
    about: 'À propos',
    support: 'Assistance',
    privacy: 'Confidentialité',
    compatibility: 'Compatibilité',
    pricing: 'Tarifs',
    related: 'À découvrir aussi',
    faq: 'FAQ',
    contents: 'Sommaire',
    sourceHeading: 'Sources',
    updated: 'Mis à jour',
    language: 'Langue',
    home: 'Accueil',
    backHome: 'Retour à l’accueil',
    readGuide: 'Lire le guide',
    allGuides: 'Tous les guides',
    learnMore: 'En savoir plus',
    footerTagline: 'Écoutez. Apprenez. Retenez.',
    copyLink: 'Copier le lien',
    linkCopied: 'Lien copié',
  },
  de: {
    skip: 'Überspringen',
    menu: 'Menü',
    download: 'Laden',
    features: 'Funktionen',
    guides: 'Anleitungen',
    compare: 'Vergleichen',
    about: 'Über uns',
    support: 'Support',
    privacy: 'Datenschutz',
    compatibility: 'Kompatibilität',
    pricing: 'Preise',
    related: 'Weitere Inhalte',
    faq: 'Häufige Fragen',
    contents: 'Inhalt',
    sourceHeading: 'Quellen',
    updated: 'Aktualisiert',
    language: 'Sprache',
    home: 'Startseite',
    backHome: 'Zur Startseite',
    readGuide: 'Anleitung lesen',
    allGuides: 'Alle Anleitungen',
    learnMore: 'Mehr erfahren',
    footerTagline: 'Hören. Lernen. Erinnern.',
    copyLink: 'Link kopieren',
    linkCopied: 'Link kopiert',
  },
  it: {
    skip: 'Salta',
    menu: 'Menu',
    download: 'Scarica',
    features: 'Funzionalità',
    guides: 'Guide',
    compare: 'Confronta',
    about: 'Chi siamo',
    support: 'Supporto',
    privacy: 'Privacy',
    compatibility: 'Compatibilità',
    pricing: 'Prezzi',
    related: 'Contenuti correlati',
    faq: 'Domande frequenti',
    contents: 'Indice',
    sourceHeading: 'Fonti',
    updated: 'Aggiornato',
    language: 'Lingua',
    home: 'Home',
    backHome: 'Torna alla home',
    readGuide: 'Leggi la guida',
    allGuides: 'Tutte le guide',
    learnMore: 'Scopri di più',
    footerTagline: 'Ascolta. Impara. Ricorda.',
    copyLink: 'Copia link',
    linkCopied: 'Link copiato',
  },
  pt: {
    skip: 'Pular',
    menu: 'Menu',
    download: 'Baixar',
    features: 'Recursos',
    guides: 'Guias',
    compare: 'Comparar',
    about: 'Sobre',
    support: 'Suporte',
    privacy: 'Privacidade',
    compatibility: 'Compatibilidade',
    pricing: 'Preços',
    related: 'Conteúdos relacionados',
    faq: 'Perguntas frequentes',
    contents: 'Conteúdo',
    sourceHeading: 'Fontes',
    updated: 'Atualizado',
    language: 'Idioma',
    home: 'Início',
    backHome: 'Voltar ao início',
    readGuide: 'Ler o guia',
    allGuides: 'Todos os guias',
    learnMore: 'Saiba mais',
    footerTagline: 'Ouça. Aprenda. Lembre-se.',
    copyLink: 'Copiar link',
    linkCopied: 'Link copiado',
  },
  zh: {
    skip: '跳过',
    menu: '菜单',
    download: '下载',
    features: '功能',
    guides: '指南',
    compare: '对比',
    about: '关于',
    support: '支持',
    privacy: '隐私',
    compatibility: '兼容性',
    pricing: '价格',
    related: '相关内容',
    faq: '常见问题',
    contents: '目录',
    sourceHeading: '来源',
    updated: '更新于',
    language: '语言',
    home: '首页',
    backHome: '返回首页',
    readGuide: '阅读指南',
    allGuides: '所有指南',
    learnMore: '了解更多',
    footerTagline: '聆听。学习。记住。',
    copyLink: '复制链接',
    linkCopied: '链接已复制',
  },
};
